env:
  global:
    - secure: hE+0Its8IiMToQpUswoxW/bcfeQgBbVW09+2FqSjYDs6dxTem+Z63Qx6VOfe/9bniqaYXAr95JB/jIHJbYTj3htJyj4BPzVeE5MWWCimuw8Li8aze8K+IskaKuJ1UJSXIzbhvd8XoQlTeKJr2ZEzKLTF2WkyvTgIIcwQiiEK1AVhZbTdwnMznId1lc4f18gb5agRduZOjfQtrz8WzRpQfWj1r7sbtQlFudee2MSSLG3f/n+sGGz57+vZkVaGQiDGwHLeIqSbkF84IXzg+PD9BGgx4sR8NUXHio7wyO2lf41xtfC2bnafn+PLg07d/5N/nYsQ6nPIlqI+l5fQUd2dGrOtwSpdqZXCogVnSB5Dub/E/MA9FtqKnUdExzr5hFlzc9qtZ+tn5XTFHC+tI+bAcPablByTrbme5MaC4EeDQSOEx+DUcDU8lDiOr1JHPiO0/zCOV+uYGhwvTvpPyfNoTFcxJAskbvZTzJpvu8Fp0dFLDaMFjY3QxBMibbPn9f+CBo4nawuWatW3sUtq6wp9ZF7/8A0/2XATPI3M6lZDGU0yicFBdPRbYWFwWNOBVWvGMVab0iqW5XAxTfHx151hM2ExQUU8mzeOZ8+/MLWrKRi3yBvNaLwqiOX7AiLaT05fS89PznAYKZyVhN9zltlPzrAjJrM6ZhM0tK/H4ULNjp4=

os: windows
language: cpp

branches:
  only:
  - master

script:
  - mkdir build
  - cd build && cmake .. && cmake --build . && ./Debug/test-main.exe
  - cmake --build . --target zip

# note: some lines have to be quoted because otherwise ": " in those lines
# makes yaml interpret them not as strings but as conditional trinary operator:
#  ? "echo \"TRAVIS_TAG" : "${TRAVIS_TAG}\"" (yes, with empty conditional part)
before_deploy:
  - git config --local user.name "Anton Voloshin"
  - git config --local user.email "ashutosh108@gmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-preview-$(date +'%Y-%m-%d')}
  - git tag -f $TRAVIS_TAG
  - "echo \"TRAVIS_TAG: ${TRAVIS_TAG}\""
  - "echo \"TRAVIS_REPO_SLUG: ${TRAVIS_REPO_SLUG}\""
  - "echo \"TRAVIS_REPO_SLUG_1: ${TRAVIS_REPO_SLUG%/*}\""
  - "echo -n \"GITHUB_API_KEY: \" && [ -z \"${GITHUB_API_KEY}\" ] && echo EMPTY || echo NOT empty"
  - git remote add gh https://${TRAVIS_REPO_SLUG%/*}:${GITHUB_API_KEY}@github.com/${TRAVIS_REPO_SLUG}.git
  - git push -f gh $TRAVIS_TAG
  - git remote remove gh

deploy:
  provider: releases
  api_key: ${GITHUB_API_KEY}
  file: vaishnavam-panchangam.zip
  skip_cleanup: true
  overwrite: true
  prerelease: true
  on:
    repo: ashutosh108/vaishnavam-panchangam
