env:
  global:
  # this defines GITHUB_TOKEN, updated 2020-01-18
  - secure: fbY6aN7FAP6dhoKfpB6SN+Gx/sENuT6GzbTRvqFX95c8bGT0ry6INRrgTo4yxaHL8RYXWW4a51zbvi4V7UfLWV91NKJkT27zn7gM3J4C0YPBRAsGjBRqsOtjLFGQSx0G2aFerZ1wNcYpbqtt3e1qahoKZefjuSwTYkdwzNQhoE4BESx7AvnL1ERkAYoaRmRQ5RYRrYFkNjPMj2ujtPEOCdknWySGXIEc9XOBrsLl971MKxdOKDbqpvhoSlSEo+UDa5NS23SXuDz3h/Lt5t/FRUKKmi3j6cQSVCHE3Dgbt4KLZrwWILk4JsLITE4KeUoXvbmiL+YHFhgKjrhgqNto/Bd3SMhU+2mez5QqV4rxkyQGWNk4C9Ra+Gqzf/CM74w4rBInfKVQk8InRT7hG7GjWaXaeF/IqYaIymRAW4vCjCfcRrzgrS/e2ILfXxK91rhh5nqXp8xQNX93QZ8as764ilfmssomFH8e4KwfCCTuLb6AV7EQ+uWqVLY5mwCrYEsmLfaRbEgVPSRvwQMxLy8Sp5IuYl9neaPBmV0lgqjvf7zH21X9JyqFv48d8ZH3md+pKQxf0B41LH7qMJsWqdM/Xl4juPO/qMTWKTGdxs7HHQI41DItQct4byBbrkc9f/g14o1s1pgWkw+yhNEfBETf2uZMgc8DHFjr5qxMfMlatm0=

os: windows
language: cpp

branches:
  only:
  - master

script:
- mkdir build
- cd build && cmake .. && cmake --build . && ./Debug/test-main.exe
- cmake --build . --target zip

# note: some lines have to be quoted because otherwise ": " in those lines
# makes yaml interpret them not as strings but as conditional trinary operator:
#  ? "echo \"TRAVIS_TAG" : "${TRAVIS_TAG}\"" (yes, with empty conditional part)
before_deploy:
- git config --local user.name "Anton Voloshin"
- git config --local user.email "ashutosh108@gmail.com"
- export TRAVIS_TAG=${TRAVIS_TAG:-preview-$(date +'%Y-%m-%d')}
- git tag -f $TRAVIS_TAG
- "echo \"TRAVIS_TAG: ${TRAVIS_TAG}\""
- "echo \"TRAVIS_REPO_SLUG: ${TRAVIS_REPO_SLUG}\""
- "echo \"TRAVIS_REPO_SLUG_1: ${TRAVIS_REPO_SLUG%/*}\""
- "echo -n \"GITHUB_TOKEN: \" && [ -z \"${GITHUB_API_KEY}\" ] && echo EMPTY || echo NOT empty"
- git remote add gh https://${TRAVIS_REPO_SLUG%/*}:${GITHUB_API_KEY}@github.com/${TRAVIS_REPO_SLUG}.git
- git push -f gh $TRAVIS_TAG
- git remote remove gh

deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file:
  - vaishnavam-panchangam.zip
  skip_cleanup: true
  overwrite: true
  prerelease: true
  on:
    repo: ashutosh108/vaishnavam-panchangam
